export const KEY = {
    A: 'a',
    B: 'b',
    X: 'x',
    Y: 'y',
    L: 'l',
    R: 'r',
    START: 'start',
    SELECT: 'select',
    LOAD: 'load',
    SAVE: 'save',
    HELP: 'help',
    JOIN: 'join',
    FULL: 'full',
    QUIT: 'quit',
    UP: 'up',
    DOWN: 'down',
    LEFT: 'left',
    RIGHT: 'right',
    PAD1: 'pad1',
    PAD2: 'pad2',
    PAD3: 'pad3',
    PAD4: 'pad4',
    STATS: 'stats',
    SETTINGS: 'settings',
    DTOGGLE: 'dtoggle',
    L2: 'l2',
    R2: 'r2',
    L3: 'l3',
    R3: 'r3',
    REC: 'rec',
    RESET: 'reset',
    WORKERS: 'workers',
    OPTIONS: 'options',
    
    // Numeric keys for J2ME games (direct mapping to match HTML data-key values)
    '0': '0',
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    
    // Special keys
    '*': '*',
    '#': '#'
}
